### ISSUE TITLE
HomeKit Certification

### ISSUE THREAD

**Issue by fullphat** [dresden-elektronik/phoscon-app-beta#124]
I'm not sure which repo to post this issue against, so apologies if this is the wrong one.

Has any consideration been given to having the Conbee II HomeKit certified?  I know there is a £ cost levied by Apple for this, and the hardware has to meet certain criteria.  I'm not sure what the cost is, and if it is one-off or rolling, but crowd-funding might be an option here?

Thanks

**Comment by ebaauw** [comment]
I cannot answer that question on behalf of dresden elektronik, but they do advertise and provide scripts to install Homebridge Hue for HomeKit support.  As the author of that Homebridge plugin I might be a bit biased, but I don't think certification by Apple would bring any value from a user perspective.

Moreover, official certification would significantly reduce HomeKit exposed functionality.  Note that the Hue bridge only exposes (Friends-of) Hue devices to HomeKit.  Signify (previously known as Philips) repeatedly claim that's due to Apple's requirements.  Also note that Apple doesn't allow some devices, like door locks, to be bridged, so any certified solution would never be allowed to expose these to HomeKit.

**Comment by fullphat** [comment]
Yes, I use homebridge-hue.  My thinking was more around if Apple were ever to prevent Homebridge from working, all the good work done here wouldn't be completely lost.

**Comment by letszb** [comment]
It is not planned to carry out an own HomeKit certification. The open source system homebridge-hue is a powerful and recommended installation to use HomeKit.

**Comment by fullphat** [comment]
Ok, thanks.  I do use homebridge-hue and it's fantastic.
