### ISSUE TITLE
no switch group created for newly added switch

### ISSUE THREAD

**Issue by andreibanaru** [dresden-elektronik/phoscon-app-beta#144]
I've just added a new Ikea TRADFRI Remote via Phoscon.
I can see it in deconz and in the "Switches" menu of Phoscon but it didn't create a remote group for me like below:

![image](https://user-images.githubusercontent.com/38393163/82747219-90a03200-9d9f-11ea-9a77-9be5d4859f80.png)

![image](https://user-images.githubusercontent.com/38393163/82747245-b75e6880-9d9f-11ea-8655-ac986231dc86.png)

**Comment by sushifrick** [comment]
> @ploebb @sushifrick This has been removed in Phoscon earlier this year. I re-opened this issue and i will move this issue to the Phoscon repository after this comment.

Thank you, I am glad to hear that! Looking forward to that.

**Comment by LestatSan** [comment]
Hi, 

I have the same issue with this two remote switches : Ikea tradfri (5button remote) and Aqara WXKG03LM. They're paired in Phocon App, but there in no "switch group created"

I have the following set up :
RPI 3b+ with raspbian strech
Phoscon app Version :  2.05.77 / 22/05/2020
Firmware : 26580700

**Comment by YKO-de** [comment]
The switch groups no longer exist. This is due to the fact that too many problems were caused by using the Switch Group and the Switch Editor at the same time. We are working on a solution. But this will still take some time.

**Comment by sushifrick** [comment]
So there is no option do bind the switches directly to the lamps to have a working setup even if the Pi is down, or am i missing something? That's a bad decision in my opinion :(.

I think Ideally the base functions, on/off, brighter/darker, (maybe even color temperature) should work without a software thinking about it. I guess this means switching back to the IKEA Gateway for me, as this does exactly that. Working light switches are way more "family-compatible" than fancy scenes, effects and schedules.

**Comment by ploebb** [comment]
Actually the switch-groups still exist, they just do not show in the new UI. However they do show in the old one.

Workaround:
Go to "Hamburger"-Menu -> Help -> Old WebbApp Version. 
![grafik](https://user-images.githubusercontent.com/5870131/88042244-eac53580-cb4b-11ea-9dc5-75e9db1aa983.png)

The old Web-UI should open. Got to "Groups"-Tab. The switch-groups should be visible there with an "Edit Members"-Button.
![grafik](https://user-images.githubusercontent.com/5870131/88042397-2bbd4a00-cb4c-11ea-89bf-da6ac9b5059f.png)

Make sure the lights have power, otherwise you cannot add them.

You can add lights to the switch group and a manually created group at the same time, however I discovered some issues as mentioned by YKO-de, such as some lights toggling on when you try to turn off everything.

**Comment by sushifrick** [comment]
> Actually the switch-groups still exist, they just do not show in the new UI. However they do show in the old one.

Thank you for this workaround and the detailed documentation @ploebb. Of course i could use the >4 years old webapp as well as I could do a rollback to an older version of the newer webapp. Both are not a good idea to rely on from my point of view. As the bindings are not used in the frontend anymore, nothing stops the developers from removing i altogether in a later update...

**Comment by MattWestb** [comment]
Then working with lights and doing "real LL bindings" is only the old web app that working if not using API or deCONS-GUI. The phoson its more or less one HA rapp application. Manup have saying that the very old web app can't being deleted (old and new large light installations) and if having first gen RaspBee / CornBee the touch link funktion it super but is not implanted the second gen dongles firmware.
@YKO-de Way not making one toggle switch LL / HA in phoscons switch editor, for switching between Lighting Link grupes / HA Switch editor for switches (best in switch editor / switch) so its being easy for the user selecting mode the switch is working. It would being good for the Aqara Opple ZB3 switches that is only working in HA mode in deCONZ (its one braking thing for my and many more users for the moment and its less expensive buying one new dongle or going for Z2M / ZHA ).

**Comment by drosenberg-gh** [comment]
Please bring back switch groups to the Phoscon app

**Comment by JasperAlgra** [comment]
I would like this also very much. After searching for many confusing hours, especially because you see many screenshots where the IKEA switches are shown as group.
Also, sometimes I get a "group 0", or "Group #random_high_id", which makes it even more confusing.

The only way a can reliable link switches to lights or power outlets is using the 'proximity' binding. That way I can use the actual physical switch and also the GUI/interface. This is ofcourse really helpfull if my 'central' computer or deconz stick would break/stops working.

So, integration of 'group binding'  (again) would be really awesome.
Just know via this ticket I found out that this was taken out deliberately. It would probably be good to mention this in the docs. Also, the "old" 2016 interface which does support the group binding could be mentioned in the official docs making it much more easy for new people to understand whats possible and what is not.

**Comment by YKO-de** [comment]
Yes it was taken out on purpose. And a concept is also being worked on so that these groups can be used again. The problem is that many users have not understood that they can only use the switch group or the switch editor. Since both can lead to misbehaviour at the same time. Therefore it was decided to hide the switch groups for the time being.

**Comment by MattWestb** [comment]
@YKO-de Way not making it configurable in the device / switch per device as i have [suggested](https://github.com/dresden-elektronik/phoscon-app-beta/issues/144#issuecomment-674425320). 
Option LL groupe funktion or HA / switch editor on etch device.

The old 2016 webapp is the only way working with lights for the moment and users is not understanding that that is giving problems for all.

**Comment by drosenberg-gh** [comment]
Any update? Are switch groups ever coming back?

**Comment by paulharken** [comment]
FYI [you can still do this easily enough, manually, using Deconz and the API.
](https://storck.io/posts/pair-tradfri-remote-to-deconz-raspbee-conbee/). I've been running it like this for a while and no problems. 

@YKO-de: You say using both can lead to misbehaviour. What specifically? If you run just a group or just a switch, will you avoid said misbehaviour? I'm running both and have no issues so far. HomeAssistant uses the groups for automation, and the switch sits on the wall as a backup in the event Deconz/HA fails. 

<img width="200" alt="Screen Shot 2022-01-22 at 8 25 12 am" src="https://user-images.githubusercontent.com/97880218/150602444-8ae073c1-d74d-49e2-9b64-3e879d70aed8.png">

**Comment by drbytes** [comment]
You spelled cumbersome wrong, you spelled it "e-a-s-i-l-y", it's spelled c-u-m-b-e-r-s-o-m-e.
I can't believe this is still an issue.
