### ISSUE TITLE
 IKEA Tradfri Dimmer connected but temperature buttons don't work

### ISSUE THREAD

**Issue by iamkarlson** [dresden-elektronik/phoscon-app-beta#176]
Hey, I was able to connect ikea dimmer with buttons. However, not all the buttons works. Brightness and on/off buttons work, temperature (< and >) buttons don't. Are there any bits of advice about making it works? 

Firmware was updated yesterday to the latest available through Phoscon app.

**Comment by gbroll** [comment]
I am just starting over from scratch with deconz, and have the same problem. Binding the side buttons on the IKEA remote to change (dim) color temperature, but nothings happens when I press either one of them. IKEA bulbs, IKEA 5 button remote. 

deconz 2.05.79 (through deconz add-on 6.2.3 in Home assistant)
Conbee, fw 0x26350500

It worked fine in my old setup. If I remember correctly, there was no switch editor so the remote was assigned to the light(s) in a different way.. (?)

**Comment by Thomas-Vos** [comment]
There appear to be different modes for the TRÅDFRI remote control. See the following how to switch between them to fix this issue: https://community.hueessentials.com/t/left-right-buttons-not-working-on-a-tradfri-remote-control-with-deconz/444

**Comment by Audio-Demon** [comment]
Hi all,
**and first of all: Big thank You for Conbee 2 - great and clutterfree addition to my Raspberry Pi running OpenHab(ian)**

I also cannot get color change working.
Neither using a group with lights and then the key assignment nor with the old web-app and the per-remote-group adding lights to remote.
and also neither with the button press or the battery-removal-method on the remote decribed in the hue-community worked for me.

This is not (yet) a dealbreaker for me, since I not use color-bulbs (yet) and the wife is happy with the warm white which at least can be selected and kept in Openhab 2 / Phoscon Conbee 2 Bridge.
But I would be happy having it in the near future.

**Another thing:**
Please provide / keep as alternative the remote-groups.
This is a **standalone feature for this great zigbee bridge**, as it will work when the bridge is not reachable.
Also I see updates to the lights in both Openhab and Phoscon App when I use the remote.
Also switching is more reliable and faster.
Is this made available through Zigbee Light Link?

From my perspective, it is vital to have this direct approach with the remotes for safety reasons.
The light-switch in the home / the childs room **must always** work.
And let's be honest: this is for the ethusiast, and the computers / PSUs / SD-Cards we have running 24/7 **will** fail.

Thanks for reading and please advice if I should address this or parts somewhere else,
and also I offer support both in testing and also writing guides.

Best,
Jan

P.S.:
This Blog also highlights that the switch can talk to the lights when the bridge "fails":
https://www.lucastechblog.com/home-automation/setup-ikea-tradfri-with-deconz-in-home-assistant/comment-page-1/#comments
and its part of my decision tree purchasing a connbee 2

**Comment by YKO-de** [comment]
The switch group leads to problems in connection with the switch editor. Which is why we have hidden it. But we are working on a concept to use them without errors. This may take some time. 

A colleague is currently working on the color temperature problem.

**Comment by jdeluyck** [comment]
Any updates?

**Comment by iaktern** [comment]
Hi, I had the same issue and solved it (with a technical solution). Phoscon is using the [deCONZ REST API](https://dresden-elektronik.github.io/deconz-rest-doc/). The switch configurations are stored as [rules](https://dresden-elektronik.github.io/deconz-rest-doc/rules/) and it only seems that the settings are a little bit messed up by Phoscon. 

The problem is that (at least my) Ikea remote controls don't send the expected long-pressed _hold_ and _release_ `buttonevent` for the left and right button (maybe there is the mentioned other [operation mode for Ikea remote controls](https://community.hueessentials.com/t/left-right-buttons-not-working-on-a-tradfri-remote-control-with-deconz/444) but I couldn't get my remote controls into this state). Instead it sends a simple `x002` click-release event after you have clicked the left or right button. With this knowledge it should be easy for the Phoscon developers to update the application. 

---

For everybody who can't wait for an update and wants to do it manually, here is how I did it. Unfortunately, the [_rules_ API documentation](https://dresden-elektronik.github.io/deconz-rest-doc/rules/) is not well described (if you read it there remain a lot of open questions: how to find the correct address of the remotes? which values can I expect by a button click? which `action.body`operations are possible? etc.) So, if you want to modify the following instructions for your environment, it's probably a little bit of trial-and-error. I use a mixture of inspecting what Phoscon does and afterwards modifying the REST API with Postman.

0. If you want, you can put the light(s) into the group that was created for the Ikea remote control. This is great if the Gateway is down, because in this case _on/off_ and _up/down_ (brightness) are still working.

![image](https://user-images.githubusercontent.com/70608052/97113008-cd25e000-16e7-11eb-9180-9cff928483ff.png)

1. Create a group which you assign the light(s) to.
2. In the switch editor, create key assignments for the left and right button to change the color temperature. Afterwards, if you have the same bug as me, you will **not** be able to actually change the color temp with the left or right button. 

![image](https://user-images.githubusercontent.com/70608052/97113441-a4ebb080-16ea-11eb-9bd0-2305eaf027b3.png)

3. We needed step 2 to create some _rules_ in the REST API. This is an easy way to find all the important values that we need to modify the rules directly in the REST API by ourself. Phoscon created 4 rules (two for each key assignment) because it assumes that the remote control will send a _hold_ (x001) and a _release_  (x003) `buttonevent`. 
   So, the first step is to find the ID of the group that you want to make the key assignments for. Do `GET /api/{{apikey}}/groups` and find the group with the correct `name`. In my case, "_Kammer_" has the group ID 11. Next, you need to find  the IDs of the 4 rules which were created by Phoscon with `GET /api/{{apikey}}/rules`. Search for "/groups/<group-id>/action", e.g. "/groups/11/action" (it is possible that you find this term more than four times, if you have other button or sensor assignments for this group). In my case, the rule-IDs are 58, 59, 60, 61. In the response, you also find: 

- in `actions.body` the operation `ct_inc` (color temperature increase) with a negative and positive value
- in the `conditions` array the correct `address` for the remote control
- in the `conditions` arrays the values `4001` (left button hold), `4003` (left button release),  `5001` (right button hold), `5003` (right button release)

![image](https://user-images.githubusercontent.com/70608052/97114319-2560e000-16f0-11eb-8747-1219059ffa91.png)

4. Our goal is to create two rules (one for the left, and one for the right button) which just increase the ct value by a small amount with every click (no long press). Therefore, we first delete the unnecessary release rules with `DELETE /api/{{apikey}}/rules/<rule-id>`, in my case rule-ID 59 and 61 (there, the `conditions` array contain `"value": "4003"` or `"value": "5003"`).

5. Last step: we modify the hold-rules to react to a click-release event. Therefore, we make a [`PUT /api/{{apikey}}/rules/<rule-id/>`](https://dresden-elektronik.github.io/deconz-rest-doc/rules/#update) with the needed body content. It is useful to copy the body from the previous response and just modify the content a little bit:

-  set `ct_inc` should be somewhere between 20-100, depending on what step size you like (it is actually not that simple since every vendor has its own ct range, so the step size varies a little bit. For example, Ikea lights can have a ct value between 250 and 454, so if you want to have for around 4 color temperatures set the value to 50. Range of my Aqara lights example: 153-370)
-  set a short `transitiontime` between 1 and 10
-  in the `conditions` array set the value of `4001` to `4002` 
-  add a new condition that prevents the buttons to exceed the allowed ct range of the light (therefore you also need to get the light-ID, which in my case is 11 (like the group ID), see example).
-  delete `created, etag, lasttriggered, owner, timestriggered` from the body content
-  repeat the rule update for the other button (`5002`) but with a negative `ct_inc` and modified exceed condition

 ```
PUT /api/{{apikey}}/rules/58/
{
    "actions": [
        {
            "address": "/groups/11/action",
            "body": {
                "ct_inc": 30,
                "transitiontime": 10
            },
            "method": "PUT"
        }
    ],
    "conditions": [
        {
            "address": "/sensors/58:8e:81:ff:fe:0b:fe:81-01-1000/state/buttonevent",
            "operator": "eq",
            "value": "4002"
        },
        {
            "address": "/lights/11/state/ct",
            "operator": "lt",
            "value": "370"
        },
        {
            "address": "/sensors/58:8e:81:ff:fe:0b:fe:81-01-1000/state/lastupdated",
            "operator": "dx"
        }
    ],
    "name": "Rule DIM-CT-UP",
    "periodic": 0,
    "status": "enabled"
}
 ```

 ```
PUT /api/{{apikey}}/rules/60/
{
    "actions": [
        {
            "address": "/groups/11/action",
            "body": {
                "ct_inc": -30,
                "transitiontime": 10
            },
            "method": "PUT"
        }
    ],
    "conditions": [
        {
            "address": "/sensors/58:8e:81:ff:fe:0b:fe:81-01-1000/state/buttonevent",
            "operator": "eq",
            "value": "5002"
        },
        {
            "address": "/lights/11/state/ct",
            "operator": "gt",
            "value": "153"
        },
        {
            "address": "/sensors/58:8e:81:ff:fe:0b:fe:81-01-1000/state/lastupdated",
            "operator": "dx"
        }
    ],
    "name": "Rule DIM-CT-DOWN",
    "periodic": 0,
    "status": "enabled"
}
 ```

**Comment by MattWestb** [comment]
Its working in deCONZ but not in Phoscon if adding the groupe 65289 in the old web app / "Wireless Light Control"  and then adding the lights in that groupe then its only to adding scenes to that groupe.

![IKEA_CT19](https://user-images.githubusercontent.com/49618193/101749089-9fe19580-3acd-11eb-9cc4-f233a78c7fda.PNG)

The saved groupe can being triggered from deCONZ. HA and from the remote.
![IKEA_CT23](https://user-images.githubusercontent.com/49618193/101749310-e0411380-3acd-11eb-8c5a-729a82993fd9.PNG)

The knowledge is handed over to the devs (Manpu) and its only implanting the logic for it in Phoscon for doing the add LL scene group it automatically.

This is the real zigbee lighting link scenes that is working also then the coordinator is offline and not the HA "Switch Editor" hack that is killing then lighting link funktionality of the zigbee network and not working then the coordinator is offline .

The question for my is do the company like getting it working or no ?

I have doing the sniffing and analysing and giving the information to the community, perhaps it was wrong giving it to DE ;-(

**Comment by johanko** [comment]
I swapped my IKEA-gateway to Conbee II and also have this issue. Everything is fine, just not the left and right buttons on IKEA Trådfri remotes for changing color on RGB bulbs and temperature on GU10 bulbs(or other warm/cold bulbs. I can set scenes, but I do want to keep my current brightness function. Is this planned to be "fixed"? Or should I just configure this in Home Assistant?

**Comment by eric-zimmer** [comment]
I have the same problem

**Comment by PatrickEhf** [comment]
This issue is still not fixed. Ikea Floalt led panel with Ikea 5 button remote. Color temperature buttons don't work at all.

**Comment by kvithayathil** [comment]
I'm getting a similar issue - when controlling IKEA GU10 Tradfri colour bulbs. I can get the 'warmer' setting to work, but not the 'colder' setting to work on the left/right buttons (if i map things like on/off to the side buttons - it seems to work)

**Comment by Athemis** [comment]
> I'm getting a similar issue - when controlling IKEA GU10 Tradfri colour bulbs. I can get the 'warmer' setting to work, but not the 'colder' setting to work on the left/right buttons (if i map things like on/off to the side buttons - it seems to work)

Same issue over here. To be more precise: Pressing the button assigned to "cooler" also triggers a change to warmer color. Pressing the button assigned to "warmer" works as expected. Using the slider in Phoscon works as well.

**Comment by knallle** [comment]
Can confirm, still not working with IKEA Trådfri E1524 remote. Have tried both methods for toggling the operating mode (a: removing the battery for 10 seconds and b: pressing the center button for 5 seconds then double clicking the outer arrows) without luck.

Conbee I
Firmware: 2.12.06 / 2021-08-19
Version: 26390500

**Comment by kolorfilm** [comment]
I also have same problem. Color temp change assigned to left and right button of remote does not change the color of the lamps.

**Comment by haukee** [comment]
Problem still exists.

2.13.04 / 19.9.2021
Firmware 26660700

Problem persist, even when using the "Schalter _beta_"-pairing in pwa-beta
