### ISSUE TITLE
Hue dimmer switch not working when Deconz unavailable

### ISSUE THREAD

**Issue by hpio** [dresden-elektronik/phoscon-app-beta#198]
## Describe the question or issue you are having
I am trying to configure Conbee II and Hue dimmer switches so that when Deconz is unavailable switches conttinue to work. I found few threads about it but for some reason I am unable to control my bulbs as soon as Deconz becomes unavailable.

All my bulbs are paired and assigned to light groups in Phoscon app, it's the same with switches.

## Screenshots
![Screenshot 2020-09-15 at 14 40 46](https://user-images.githubusercontent.com/8372645/93217877-7d0b4380-f761-11ea-9532-f7d3da0eab06.png)
![Screenshot 2020-09-15 at 14 40 56](https://user-images.githubusercontent.com/8372645/93217885-7f6d9d80-f761-11ea-9086-b1fd15fba23f.png)

## Environment

deConz version: *2.05.80 / 14/08/2020*
firmware version *264A0700*

 - Host system: Unraid
 - Running method: Home Assistent deCONZ Add-on / Marthoc Docker container
 - Firmware version: (26xxyy00)
 - deCONZ version: 264A0700
 - Device: ConBee II
 - Do you use an USB extension cable: yes

## Additional context
I am fairly confident that in the past I was able to control lights even with Deconz unavailable but I am unable to make it work again

**Comment by hpio** [comment]
hi @Mimiix , would you mind explaining or pointing me to the docs how I can achieve that using old web env? Wasn't aware there was an old/new envs

**Comment by hpio** [comment]
Actually, I managed to access the old interface and I am pretty sure I've never used it. When I got switches working with Deconz unavailable all configuration was done using the new interface

**Comment by Mimiix** [comment]
Yep. This feature was in Phoscon before but got removed. Groups in Phoscon are **not** zigbee groups. I already made a request: #173 

How to: 

On the old web-app you have a page called "groups". Here you should see the remotes called something like "RWL". Add the lights to those groups and you should be fine.

The controls would work as the HUE Dimmer switch intented. 

After that, remove the groups you made. T

**Comment by popy2k14** [comment]
@Mimiix 

I found this thread because on my up to date deconz installation in phoson are now many RWL groups after upgrade from 2.12 to 2.14.01.

Does that mean it's now possible also with Phoscon, or do i have to use the old interface?

Just to be sure and not mess someting up:

- On the old web-app you have a page called "groups".
- Here you should see the remotes called something like "RWL".
- Add the lights to those groups and you should be fine.
- When deconz is offline, The controls would work as the HUE Dimmer switch intented.
- After that, remove the groups you made.

Is that correct?
Also to delete the RWL groups afterwards -> the would be good if that works, because i dont want to see them :-)

thx
