### ISSUE TITLE
[Device Support Request] Tuya Temperature sensor RH3052

### ISSUE THREAD

**Issue by icservis** [dresden-elektronik/phoscon-app-beta#203]
Please can you add sensor support do Phoscon?
<img width="526" alt="Snímek obrazovky 2020-09-20 v 9 00 51" src="https://user-images.githubusercontent.com/948851/93706055-f2409500-fb22-11ea-87f8-18333df10c97.png">
<img width="428" alt="Snímek obrazovky 2020-09-20 v 9 00 02" src="https://user-images.githubusercontent.com/948851/93706057-f7054900-fb22-11ea-92b4-2d41812f6286.png">

**Comment by robehem** [comment]
I also would love to have this sensor added.

**Comment by elnigno** [comment]
I would also like to have support for this. Can the issue be reopened?

**Comment by Lorenzino86** [comment]
Me too... if possible have complete integration.

**Comment by manup** [comment]
There was this device request in the deconz-rest-plugin repository: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3690

Are the modelid and manufacturername the same for yours?

Since this is a standard sensor it should already be displayed in the Phoscon App. A while ago this was made possible as generic approach to display sensors.

**Comment by Lorenzino86** [comment]
I apologize, after the Phoscon update, everything has been updated!
Thanks.
