### ISSUE TITLE
Connect to default gateway (or last used one)

### ISSUE THREAD

**Issue by ooii** [dresden-elektronik/phoscon-app-beta#22]
Hi, 

I used to have one ConBee and one Hue gateways. When connecting to Phoscon app, I [see](https://akalat.fr/1a8e3f989ee354176e81b4f595ed5cc9) both on the first screen. Now I have disconnected the Hue bridge, I continue seeing it but grayed.
Is it possible to add the ability to connect directly either to the last chosen gateway or to the one defined as default?
In the meanwhile, how can I remove the Hue bridge from this first screen? I tried to clear my cache bit it did not do it.
Thanks.

**Comment by manup** [comment]
>Is it possible to add the ability to connect directly either to the last chosen gateway or to the one defined as default?

If you make a bookmark to the `http://<gw-ipaddress>/pwa/index.html` page it should open directly (as long as you don't logout).

>In the meanwhile, how can I remove the Hue bridge from this first screen? I tried to clear my cache bit it did not do it.

Yes this needs to be fixed so that too old bridges won't be visible anymore.

Meanwhile you can clear the related cache in the browser developers console (F12) by executing this command:

`localStorage.removeItem('app.gateways')`

**Comment by ooii** [comment]
Thanks.
