### ISSUE TITLE
upgrade of phoscon app / firmware is not available from web - manual?

### ISSUE THREAD

**Issue by elpaso666** [dresden-elektronik/phoscon-app-beta#220]
Hi,

my phoscon web app says: 2.05.71 / 9/14/2020, after I did:
_sudo apt-get update
sudo apt-get upgrade_
after this i see;
_Setting up deconz (2.05.81-raspbian-buster-stable) ..._

can some one help me (I am linux noob) how to update the phoscon to latest version while not breaking the current setup? also the firmware upgrade might make sense as I am on - 26490700 which is also statet as _version is up to date_

thank you a lot!
Jakub

**Comment by letszb** [comment]
You can choose a stable or a beta APT repository for this updating way.
https://www.phoscon.de/en/conbee2/install#raspbian

Otherwise you can do a dpkg update a describe here.
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually#update-in-raspbian
The update for the firmware is also described there.

In some cases there is also a possibility to update the firmware in the Phoscon App.
https://www.phoscon.de/en/support#update-firmware-conbee2-raspbee2
