### ISSUE TITLE
Xiaomi WXKG12LM hold event mapping in app

### ISSUE THREAD

**Issue by thomasgermain** [dresden-elektronik/phoscon-app-beta#233]
Hello,

according to the doc https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-WXKG12LM, the xiaomi WXKG12LM switch is able to emit `hold` event.

I would like to be able to map the hold event with the phoscon app. My end goal is to dim the light while holding to button.

Thanks,

Thomas

**Comment by MPA-DE** [comment]
Hello,
yes the switch is already supported.
You can set this in the "Switch Editor"
Find it under "Group" --> "Edit" --> "Switch-Editor" --> "Link Switch" --> Xiaomi

**Comment by thomasgermain** [comment]
Hello,

yes sure, my switch is already linked to a light group (and this is working well). But I would like to assign the `hold` event. And I don't have this option through the app, see:

![image](https://user-images.githubusercontent.com/12560542/97558155-04dca280-19dc-11eb-9c46-584c83ce0540.png)

According to the doc, there is also the hold and release event, so i'm expecting to be able to assign these events through the app.

My end goal is to mimic a "real" push button on a wall -> you keep holding it and it's dimming the light

**Comment by StephanStS** [comment]
@MPA-DE:  
See #70: The events 'long single press' and 'long single release' are these which thomasgermain mentioned.

**Comment by YKO-de** [comment]
Do you mean this...
![image](https://user-images.githubusercontent.com/55535297/97966194-c704c300-1dbb-11eb-9703-764fbec8ee7f.png)

The hold event is for dimming.

**Comment by StephanStS** [comment]
At least the button events need to be extended there with "long single press" and "long single release":
![grafik](https://user-images.githubusercontent.com/57687516/97969910-fe29a300-1dc0-11eb-8fb7-0ef3081466ba.png)  
Then you can assign long presses to actions.
The "long press release" is less relevant if you think about dimming, because every "long single press" has a "long single release" afterwards. With different events you only can define the instant of time of the fired event.

But your proposal fits to a different (and important) use case: Change values based on several events.  
I would not name it "Long press dim, short press on/off", because the on/off is linked with the first tab "On / off" at the top. I would rather name it "Long press dimming" only.

**Comment by thomasgermain** [comment]
@YKO-de 
This is exactly that, I searched for hours before posting the issue, maybe I was drunk ? 😅, just tested it, working perfectly.

@StephanStS 
Actually, I don't mind of the `long press release` event itself. But the function I want is already existing. I think I was not clear enough in my first post. My use case is quite straightforward:
- first hold event -> switch on and get brighter and brighter
- release
- second hold event -> get darker and darker and switch off. 

So the release event is actually used internally toggle the functionality (brighter or darker).
