### ISSUE TITLE
Support for Sengled Smart Light Switch E1E-G7F

### ISSUE THREAD

**Issue by stevenwfoley** [dresden-elektronik/phoscon-app-beta#259]
Initial support for the Sengled Smart Light Switch E1E-G7F in deconz was added in v2.6.0-beta, but its not showing up properly in phoscon. The switch is a 4 button switch, similar to the Philips Hue Dimmer (on, dim-up, dim-down, off), but its showing up as a generic switch in the Switches section. Its also not showing up in the switch editor interface, so I cannot assign any button actions.

**Comment by YKO-de** [comment]
There is no individual image for this switch yet. Hence the generic one. I can take a look at the switch editor. Can you tell me the button events of the switch?

**Comment by stevenwfoley** [comment]
I would be happy to provide you with the button events, but I'm not sure what you're asking for. Could you please elaborate or provide an example of how I would obtain the button events.

**Comment by SwoopX** [comment]
@stevenwfoley Please check the original issue for the requirements.

**Comment by YKO-de** [comment]
Okay. There are several possibilities. One is:
- Press F12 in the Chrome browser
- Press the Network Tap
- Press the switch (all keys short and long)
- After each click you choose the event in the left column
- Then look at Preview on the right for state: {buttonevent: ?, ...} and write down which button you pressed and whether it was short or long.

![image](https://user-images.githubusercontent.com/55535297/102486792-e2751600-4069-11eb-8046-4389f0cfb6f5.png)

I suppose from top to bottom. 
1002, 1001, 1003
2002, 2001, 2003
3002, 3001, 3003
4002, 4001, 4003
But since I don't have the switch, I can't check.

**Comment by SwoopX** [comment]
There's currently no button map available :/

**Comment by YKO-de** [comment]
@SwoopX What do you mean? The switch must deliver some kind of events. :/

**Comment by SwoopX** [comment]
@YKO-de you only get the button event numbers, if there's a button map available in `button_maps.json`. Otherwise, you get the raw commands.

**Comment by YKO-de** [comment]
I see. So that would have to be deposited first. OK. 
@stevenwfoley Then my instructions are useless.
