### ISSUE TITLE
Creating backup failed!

### ISSUE THREAD

**Issue by GallusMax** [dresden-elektronik/phoscon-app-beta#321]
bummer - what is left to restore, when even the backup fails during creation? 
on the other hand its less frustrating than failing on restore 8-/

please give a hint which log could be helpful. activating ERROR and ERROR_L2 resulted in nothing.

Version: 2.09.01 / 23.12.2020
Firmware: 26680700

screenshot attached.
![Screenshot_2021-02-02 Phoscon App](https://user-images.githubusercontent.com/5851035/106603779-0da2be80-655f-11eb-8274-5954d2d5621c.png)

**Comment by ChrisHae** [comment]
This normaly happens when the Conbee2 is not connected or the Phoscon App is not reachable or the API Key of the app is not valid anymore.
What does the Settings/Gateway page say? As far as I can recognize it shows the FW version and the device name so the Conbee2 is connected.

Perhaps try to log out and login again to check if the app work correct.

Another guess would be the network settings of deCONZ are messed up. Are you able to pair and control lights?
If not a screenshot of the deCONZ network settings could be usefull.
