### ISSUE TITLE
[Device Request] ZigBee (tuya) Smart Switch

### ISSUE THREAD

**Issue by Armag3ddon** [dresden-elektronik/phoscon-app-beta#393]
https://www.ebay.de/itm/124165611541 (I bought the 2 button version)
Model: YSR-ZSW

deCONZ does recognise the device:
![switch](https://user-images.githubusercontent.com/1497574/120370224-9adeff80-c314-11eb-896a-9ec80900cc90.jpg)

If possible to support, it'd be greatly appreciated by me.

**Comment by SEK-DE** [comment]
@Armag3ddon we try to integrate a tool, which make you can add nearly every type of switch, with generic pictures of the switch in advance. Because the problem especially with tuya is, that they use the same model ID for different devices. So it takes a bit more time. Please be patient and look out for the upcomming change-logs in the next versions.
