### ISSUE TITLE
How to add scene other than motion sensor with light

### ISSUE THREAD

**Issue by marvin-SL** [dresden-elektronik/phoscon-app-beta#408]
Hi,

I have some relays, and temperature sensors from sonoff (zbmini and snzb-02). They works well in phoscon, but I want to add 3 scenes and I can't figure how to do so :
Scene 1- when humidity reach X, turn on relay1 (recognized as light switch).
Scene 2- when humidity reach Y, turn off relay1
scene 3- on monday and friday, turn on relay2 for X hours.

All I can do is scene for motion sensor (turn on/off light with fade in/out).Or maybeI can't do that in phoscon? 

Version 2.12.3-beta

Thanks

**Comment by SEK-DE** [comment]
Hi @marvin-SL,

it´s not possible at the moment in our app. I will mention that in our next programmer meeting, becouse it will be helpfull in the future. For now, you can implement the needed scene over a HA system like IO-Broker or Home Assistant.

I will let this post open until i get something new for you.

**Comment by marvin-SL** [comment]
Hello @SEK-DE, thank you for your reply, I'll keep an eye on phoscon for that.
Thanks in advance

**Comment by phluorine** [comment]
@marvin-SL I'm trying to implement the same scenario. Both devices work in HomeKit via Homebridge and can be programmed to activate at a certain Rel Humidity threshold (you have to write it as a shortcut) but it'd be super to get this implemented at the Zigbee level. The other option is the non-home automation route-- There are purpose-built bathroom fan switches (eg from [Leviton IPHS5-1LW](https://www.amazon.com/Leviton-IPHS5-1LW-Humidity-Sensor-Control/dp/B00H3QQD64/)) that do this. One advantage of the automation route is that the sensor can be placed high on the wall so that it detects when warm, humid air is still pooled near the ceiling even if eg you've opened a door and let some of the steam out.

Related but off-topic have you gotten the switch _input_ to work? I haven't, but at least I've finally gotten my SNZB-01 to work correctly and I use it as an on/off toggle in Phoscon (seems like the new deCONZ beta 2.12.6 fixed Phoscon not letting me use it as a switch.) Oddly Homekit doesn't support it but that's not a big deal.

Anyway, whenever I add the ZBMINI to Phoscon, even using the sensor (let alone the switch or light) panel, it still shows up as a dumb "On/off light". I've been muddling through trying to understand how all this works behind the scenes and unfortunately it's not clear to me how to get deCONZ/Phoscon to recognize it as an "On/off light switch" rather than an "On/off light". 

<img width="832" alt="Screen Shot 2021-08-28 at 09 02 13" src="https://user-images.githubusercontent.com/4112505/131220598-1dc8c642-8f78-4707-9537-beb7cc8bf5b5.png">
<img width="803" alt="Screen Shot 2021-08-28 at 09 02 55" src="https://user-images.githubusercontent.com/4112505/131220599-5832ea55-4894-4460-9130-52ad7bce25d7.png">

**Comment by SEK-DE** [comment]
Hey folks,

also a feature where our developers are already into it. 
We´ve planed some major developement and changes for the next months, also this feature is planed. 
Please be patient, i can´t promise that it will part of the next update, but it will come sooner or later.
