### ISSUE TITLE
Is deconz compliant with google home ?

### ISSUE THREAD

**Issue by minscof** [dresden-elektronik/phoscon-app-beta#55]
This is a question about interoperability between phosco/deconz and google home. The goal is to speak and command equipment through the google home first for the voice, and next though the deconz/phoscon app to do the command.

Thank you

**Comment by hhkarsten** [comment]
I kinda have the same question but since the one above has been unanswered/ignored for some month now I reckon deconz/phoscon is either not compatible with Google Home / Nest or it's so obvious how to do that, that nobody wants to answer

**Comment by michaelblight** [comment]
The deConz API is the same as the Philips Hue API, so you should be able to add it to Google Assistant by finding it by adding Philips Hue in Home Control. However, for me it doesn't work.

To try to isolate the problem I tried a few things...

If I use the Hue iOS app, it cannot automatically find deConz, but I can enter the IP address. However it cannot connect, even after clicking "Authenticate App" in Phoscon.

If I use the Hue Essentials iOS app, it also cannot find deConz automatically. However, for this app when I enter the IP address and authenticate in Phoscon, it is happy to connect. This is with the bridge set to Philips Hue, as Hue Essentials also supports deConz.

I read you can connect if you also have a physical Hue bridge. I do, but it's v1. I have to add it using the old app, and it won't let me add deConz because that needs the new app. I suspect it wouldn't work as per the above anyway.

**Comment by minscof** [comment]
I found a solution. You have to install homebridge and 2 plugins
- homebridge-hue
- homebridge-gsh

You can also install homebridge-alexa plugin.

Hope this can help.

**Comment by HomerSp** [comment]
Thank you, this has worked for me. Setting up homebridge was a bit of work, but it's definitely worth it!
When setting up homebridge-hue, make sure to actually expose some resource types or you won't actually see anything in the Google Home app.

**Comment by minscof** [comment]
Good news, we can closed this issue

**Comment by oywino** [comment]
It's impossible to add Phillips Hue in Google Home unless one actually have a Hue Bridge HUB.
So, should I run and buy a Hue Bridge just to be able to add deConz devices to Google Home?

**Comment by ofh** [comment]
Hi
Is it possible to setup homebridge on a Ubuntu deconz installation?
Any link?
BR
Ofh

**Comment by ofh** [comment]
Have found the solution.

**Comment by markszabo** [comment]
@ofh would you mind sharing your solution?

**Comment by ofh** [comment]
What specific do you think about?
Br

lør. 15. jan. 2022 11.40 skrev Mark Szabo ***@***.***>:

**Comment by markszabo** [comment]
You asked about setting up homebridge on a Ubuntu deconz installation, and then commented that you found a solution, and I was wondering what that solution was.
