### ISSUE TITLE
How to connect the Xiaomi / Aqara Cube with Phoscon?

### ISSUE THREAD

**Issue by Maddinthebrain** [dresden-elektronik/phoscon-app-beta#56]
Hi, 

I bought a Xiaomi Cube. But I  cannot connect it to the Conbee Stick. First I start the connection process for new sensors in Phoscon. Then I press the link button of the cube for about 5 seconds. During this the blue LED is on. After releasing the button the LED ist flashing some times, in a way that the connection process is starting, But in Phoscon nothing happens. 

I have the latest beta of Phoscon. The firnware of the conbee stick is also the latest one.

Any help is aprreciated!

Martin

**Comment by CC1337** [comment]
Trigger the reset button each second (short press), shake the cube, flip it 90° etc. to trigger events and keep it awake. Go very close to the ConBee stick. I also had one where the battery was close to empty. Replace it.

**Comment by CC1337** [comment]
As I just got the hint while having issues as well, also rotate it while pairing :)

**Comment by StephanStS** [comment]
@Maddinthebrain: Do you only plan to use phoscon, or also other tools like Node-RED (RedMatic,...) etc? In these tools you can see more in detail what happens: The cube ("Zauberwürfel") is represented as two nodes which have to be paired at the same time. Like @CC1337 mentioned above: You need e.g. to shake the cube (sensor instance #1) and also to turn the cube (sensor instance #2) during the pairing so that phoscon recognizes not only one of the two sensor instances.
Are you familiar with RESTful API commands? Then you could also see there these two instances.

We could also do a short telecon (e.g. via Jitsi), then I could show you this on my installation.

**Comment by Maddinthebrain** [comment]
@StephanStS Well since a new version of deconz it works fine now!
