### ISSUE TITLE
How to activate scene depending on daylight with motion sensor (rule)

### ISSUE THREAD

**Issue by mgrn0** [dresden-elektronik/phoscon-app-beta#95]
How (if at all) can I activate a scene for lights activated through a sensor rule, using a motion sensor? Use case is that I want to have a warm light during nighttime and a colder, brighter light during daylight but at all times activated through a motion sensor. 

I digged through the manuals and the issues here but could not find any answer. When using the Hue essentials app the lights wont turn on or off at all so I try to stay within the Phoscon app to create all rules and set settings.

**Comment by MPA-DE** [comment]
You need a motion sensor and you can adjust it with the Phoscon app to switch on warm or cold white light.
Instructions for controlling motion detectors can be found here: https://phoscon.de/de/app/doc#group-edit-sensors-motion-de

**Comment by mgrn0** [comment]
@MPA-DE forgive me but I cannot find the information you described: I can find the light LEVEL but no instruction about light TEMPERATURE depending on time of the day? I looked through the manual a couple of times (of course) before opening the issue here...

**Comment by MPA-DE** [comment]
To use the lamps with different color temperatures as motion detectors, you can try the following:

Create a scene (for example: early, cold white) and switch it off after 1 minute by Schedules.
Then create another scene for the evening (for example: evening, warm white).
Then let these lights go on or off using the timer.
Next, create a sensor control, adjust the brightness as desired, select "Always active" under "Setting".

Or you can create 2 sensor controls with different brightness levels and then set them to evening and daytime (using the cogwheel symbol at the bottom of the page) and select a motion detector, so that the hook at the back of the motion detector is shown as active.
