### ISSUE TITLE
Everytime new password logout of Phoscon

### ISSUE THREAD

**Issue by netzbus** [dresden-elektronik/phoscon-app-beta#99]
I have the problem that when I log out of phoscon app and log in again it always wants to define a new password.
Whatever password I choose, phoscon app states "login denied". The only way to came arround is to delete "/home/pi/.local/share/dresden-elektronik/deCONZ/zll.db".
Then defining new password is working but after logout the drama reconvenes

Hardware is:
Raspberry 3 with Raspbian
Conbee 2 Stick

**Comment by YKO-de** [comment]
Is the problem still there?

**Comment by dicer** [comment]
Yeah, I have the same problem: Installed in a docker container, which exposes the http port at 9080, but the firewall blocks that. Instead I connect via ssh port forward to the docker machine and go to http://127.0.0.1:9080
That works and the gateway is found, but I am asked to input a new login password.
In the Firefox network log you can see, that the webpage is trying to connect to the actual IP of the machine the docker image is running on and not to 127.0.0.1 as it should.
This was working just fine when I set the whole thing up! Now I seemed to be logged out and can not log in anymore!

**Comment by dicer** [comment]
I should add: In Firefox it seems to have recovered. I can login there.
It did work in Chrome as well, but there I'm still stuck

**Comment by Myhlamaeus** [comment]
I have the same issue: phoscon always thinks that I have to set a new password while using SSH port forwarding; however, I can confirm that it works when I connect directly with the remote host.

After trying around a bit, I figured out that it is related specifically to localhost and the loopback device, as using eg phoscon.localhost (which both Firefox and Chromium resolve to 127.0.0.1) instead fixes the issue (but using 127.0.0.1 directly is also broken.)

As an aside, at first I thought that this might be caused by some stray requests to `http://localhost/config` instead of `http://localhost:8080/config` (with 8080 being the port which is forwarded to deconz's socket), which probably shouldn't be there.

**Comment by dicer** [comment]
phoscon.localhost works for me too (Chromium)
I still see a lot of requests to the actual IP in the network logs though. So it still tries to connect directly, but something else is different when using phoscon.localhost instead of 127.0.0.1.

Also: When using 127.0.0.1 and I leave the window open long enough, it *eventually* just starts working again! I still have a valid cookie though, so I don't know whether login itself works. I just know that I can access the sensors again after a while.

**Comment by srtxema** [comment]
another one with the same problem. In localhost:8080 and phoscon.de/app
